import { useState } from 'react';
import { DeityGallery, FactGrid, NameActivity, ObjectCard, PageHero, PageNext, QrGrid, Quiz } from './components';
import { timelineEras } from './data';

export function HomePage() {
  return <main id="conteudo">
    <section className="hero home-hero" id="inicio" aria-labelledby="home-title"><div className="wrap home-hero-grid"><div className="hero-copy"><div className="eyebrow">Amostra cultural · Museu digital</div><h1 id="home-title">Uma viagem<br />ao <em>Egito Antigo</em></h1><p>Do rio que alimentou uma civilização aos monumentos que ainda nos impressionam. Explore as páginas, encontre pistas e siga a história até o Egito de hoje.</p><a className="cta" href="#experiencia">Comece com seu nome <span>↓</span></a></div><figure className="home-hero-art"><img src="/assets/egypt-hero.jpg" alt="Paisagem ilustrada do Nilo entre palmeiras e as pirâmides de Gizé ao entardecer" /><figcaption><span>PAISAGEM EGÍPCIA</span><strong>O Nilo encontra o deserto</strong></figcaption></figure><div className="home-hero-meta"><span>Uma amostra para percorrer no seu ritmo</span><a href="#explorar">Conheça as cinco estações ↓</a></div></div></section>
    <NameActivity />
    <section className="opening" aria-labelledby="welcome-title"><div className="wrap opening-grid"><div><div className="section-kicker">Bem-vindos, viajantes</div><h2 className="section-title" id="welcome-title">Um museu para explorar</h2><p className="intro">Leia as placas, observe os objetos e teste o que aprendeu. A história egípcia é longa, diversa e continua viva: esta viagem atravessa muitos períodos, não apenas a época dos faraós.</p></div><div className="quote">“Escaneie os QR Codes e embarque em uma viagem de mais de 5.000 anos pela história do Egito.”<span>— convite à exposição</span></div></div></section>
    <section className="stations" id="explorar" aria-labelledby="stations-title"><div className="wrap"><div className="section-kicker">Explore por tema</div><h2 className="section-title" id="stations-title">Cinco caminhos pela história</h2><p className="intro">Escolha um tema para começar. Depois, use a linha do tempo e observe os objetos; no fim, teste as pistas no quiz.</p><div className="cards">
      <a className="card" href="/nilo.html"><img className="card-image" src="/assets/nile-boat.jpg" alt="" loading="lazy" /><div className="icon">01</div><h3>O Nilo e a vida cotidiana</h3><p>Água, campos férteis, barcos e os ritmos do ano.</p></a>
      <a className="card" href="/monumentos.html"><img className="card-image" src="/assets/egypt-hero.jpg" alt="" loading="lazy" /><div className="icon">02</div><h3>Pirâmides e monumentos</h3><p>Gizé, templos, tumbas e o trabalho de construir.</p></a>
      <a className="card" href="/escrita.html"><img className="card-image" src="/assets/hieroglyphs.jpg" alt="" loading="lazy" /><div className="icon">03</div><h3>Escrita e crenças</h3><p>Hieróglifos, a Pedra de Roseta e diferentes tradições religiosas.</p></a>
      <a className="card" href="/linha-do-tempo.html"><img className="card-image" src="/assets/egypt-hero.jpg" alt="" loading="lazy" /><div className="icon">04</div><h3>Linha do tempo</h3><p>Da unificação do reino às muitas mudanças da história egípcia.</p></a>
      <a className="card" href="/egito-hoje.html"><img className="card-image" src="/assets/cairo-contemporary.jpg" alt="" loading="lazy" /><div className="icon">05</div><h3>Egito de ontem e de hoje</h3><p>Uma ponte entre o passado e um país contemporâneo.</p></a>
    </div></div></section>
    <section className="timeline" id="curiosidades" aria-labelledby="dates-title"><div className="wrap"><div className="section-kicker">Um mapa do tempo</div><h2 className="section-title" id="dates-title">Algumas datas para se localizar</h2><FactGrid facts={[
      { title: 'c. 3100 a.C.', text: 'Unificação política do Alto e do Baixo Egito.' },
      { title: 'c. 2600–2500 a.C.', text: 'Grandes pirâmides de Gizé no Império Antigo.' },
      { title: 'c. 1550–1070 a.C.', text: 'Período do Novo Império.' },
    ]} /><a href="/linha-do-tempo.html" className="cta">Ver linha do tempo completa →</a></div></section>
    <section className="stations" aria-labelledby="objects-title"><div className="wrap"><div className="section-kicker">Observe as peças</div><h2 className="section-title" id="objects-title">O passado em detalhe</h2><p className="intro">Imagens de objetos preservados em coleção. Cada fotografia leva à ficha do museu e inclui informação de licença.</p><div className="object-gallery">
      <ObjectCard image="/assets/tutankhamun-head.jpg" alt="Cabeça escultórica de Tutancâmon, em calcário endurecido, vista frontal" title="Tutancâmon" text="Cabeça escultórica do jovem faraó · Novo Império" credit="The Met, ficha 544690 · inventário 50.6" href="https://www.metmuseum.org/art/collection/search/544690" />
      <ObjectCard image="/assets/cleopatra-queen.jpg" alt="Estátua de uma rainha do período ptolemaico, em pedra clara" title="Uma rainha ptolemaica" text="A identificação com Cleópatra VII é possível, mas não comprovada." credit="The Met, ficha 547702 · inventário 89.2.660" href="https://www.metmuseum.org/art/collection/search/547702" />
      <ObjectCard image="/assets/hieroglyphs.jpg" alt="Relevos com linhas de hieróglifos egípcios esculpidos em pedra" title="Marcas na pedra" text="Um bloco inacabado preserva sinais e etapas do trabalho." credit="The Met, objeto 20.3.160" href="https://www.metmuseum.org/art/collection/search/562008" />
      <ObjectCard image="/assets/osiris.jpg" alt="Estatueta de Osíris, figura de pé usando coroa e segurando símbolos de poder" title="Osíris" text="Divindade associada à realeza e à vida após a morte." credit="The Met, objeto 04.2.579" href="https://www.metmuseum.org/art/collection/search/570658" />
    </div></div></section>
    <section className="stations" id="qr-estacoes" aria-labelledby="qr-title"><div className="wrap"><div className="section-kicker">Leve a exposição com você</div><h2 className="section-title" id="qr-title">QR Codes da exposição</h2><p className="intro">Cada código abre uma página diferente. Na amostra, os visitantes também podem tocar nos cartões para abrir o conteúdo.</p><QrGrid /><p className="qr-note">Os códigos já apontam para o endereço público do site. Use “Imprimir” no navegador para preparar esta área como folha de apoio.</p></div></section>
    <Quiz />
    <section className="closing"><div className="wrap"><h2>A viagem continua no Nilo.</h2><p>Obrigado por visitar nossa amostra cultural!</p></div></section>
  </main>;
}

function NileMap() {
  return <><div className="mapbox" style={{ maxWidth: 430, background: '#182536' }}><svg viewBox="0 0 330 360" role="img" aria-label="Mapa esquemático do Egito com o rio Nilo, Cairo, Luxor, Assuã e o mar Mediterrâneo"><path d="M108 26 239 41 270 107 250 151 271 224 218 302 147 337 113 279 88 224 70 163 49 108 70 56Z" fill="#bb8751" stroke="#f0cc8b" strokeWidth="2" /><path d="M174 316 168 272 171 231 164 191 168 151 164 111" fill="none" stroke="#82c9c2" strokeWidth="7" strokeLinecap="round" /><path d="m164 111-37-24m37 24 2-38m-2 38 43-20" fill="none" stroke="#82c9c2" strokeWidth="5" strokeLinecap="round" /><circle cx="168" cy="220" r="5" fill="#fff0c8" /><text x="180" y="224" fill="#fff0c8" fontSize="12">Luxor</text><circle cx="170" cy="280" r="5" fill="#fff0c8" /><text x="181" y="284" fill="#fff0c8" fontSize="12">Assuã</text><circle cx="165" cy="132" r="5" fill="#fff0c8" /><text x="177" y="136" fill="#fff0c8" fontSize="12">Cairo</text><text x="36" y="30" fill="#c8c0ae" fontSize="10">MAR MEDITERRÂNEO</text></svg></div><p className="map-note">O delta fica ao norte; Assuã fica ao sul. A costa do Mar Vermelho está a leste.</p></>;
}

export function NilePage() {
  return <main id="conteudo"><PageHero page="nile" eyebrow="Território e cotidiano" title="O rio que atravessa o deserto">O Nilo ligava comunidades, irrigava plantações e oferecia uma rota de viagem pelo vale egípcio.</PageHero><section className="page-content"><div className="wrap">
    <section aria-labelledby="vida-no-nilo"><div className="page-grid"><div><div className="section-kicker">Uma paisagem de contrastes</div><h2 id="vida-no-nilo">Água, terra fértil e deserto</h2><p className="body-copy">A maior parte do Egito recebe pouca chuva. Por isso, durante milênios, muitas cidades e áreas cultivadas se concentraram perto do Nilo. Quando as águas inundavam o vale, deixavam umidade e sedimentos que ajudavam a preparar os campos.</p><p className="body-copy">A agricultura dependia do rio e do trabalho coletivo: canais e bacias ajudavam a conduzir e reter água. Grãos, legumes, tâmaras e linho faziam parte da economia e da alimentação em diferentes épocas.</p><div className="callout"><p><strong>Olhe no mapa:</strong> o Nilo corre do sul para o norte. Ao chegar ao Mediterrâneo, abre-se em vários braços e forma o delta.</p></div></div><figure><img src="/assets/nile-boat.jpg" alt="Fotografia histórica em sépia de um barco a vela no Nilo" loading="lazy" /><figcaption className="photo-credit">“Nile Boat, Egypt”, fotografia de 1851. <a href="https://www.metmuseum.org/art/collection/search/286266" target="_blank" rel="noreferrer">The Met, ficha 286266 · inventário 2005.100.1283</a> · imagem CC0.</figcaption></figure></div>
      <FactGrid facts={[{ title: 'Transporte', text: 'Barcos ligavam assentamentos e ajudavam a transportar pessoas e mercadorias.' }, { title: 'Estações', text: 'O calendário agrícola se organizava em torno da cheia, do plantio e da colheita.' }, { title: 'Uma história longa', text: 'O ritmo do rio mudou com barragens modernas, incluindo a Grande Barragem de Assuã.' }]} />
    </section><section aria-labelledby="mapa"><h2 id="mapa">Encontre o Nilo</h2><p className="body-copy">Mapa esquemático: mostra a direção geral do rio, o delta e algumas cidades; não está em escala.</p><NileMap /></section>
    <PageNext previous={{ text: 'Voltar ao museu', href: '/index.html' }} next={{ text: 'Próxima estação: monumentos', href: '/monumentos.html' }} />
  </div></section></main>;
}

export function MonumentsPage() {
  return <main id="conteudo"><PageHero page="monuments" eyebrow="Pedra e memória" title="Monumentos feitos para durar">Pirâmides, templos e tumbas registram crenças, poder e a capacidade de organizar grandes projetos.</PageHero><section className="page-content"><div className="wrap"><section aria-labelledby="piramides"><div className="page-grid"><div><div className="section-kicker">Gizé · Império Antigo</div><h2 id="piramides">As pirâmides de Gizé</h2><p className="body-copy">As pirâmides de Quéops, Quéfren e Miquerinos foram construídas durante a 4ª dinastia, aproximadamente entre 2600 e 2500 a.C. A Grande Pirâmide de Quéops é a única das Sete Maravilhas do Mundo Antigo que ainda permanece em grande parte de pé.</p><p className="body-copy">Erguer um monumento desse porte exigiu planejamento, transporte de materiais e muitos trabalhadores. Escavações encontraram um assentamento ligado à construção dos complexos de Quéfren e Miquerinos, com vestígios de moradias e alimentação. Por isso, é simplista repetir a ideia de que as pirâmides foram construídas apenas por pessoas escravizadas.</p><div className="callout"><p><strong>A Esfinge:</strong> a Grande Esfinge guarda o planalto de Gizé. Sua associação com o faraó Quéfren é comum entre pesquisadores, embora detalhes sobre sua construção e função ainda sejam debatidos.</p></div></div><figure><img src="/assets/giza-plan.svg" alt="Esquema do planalto de Gizé com as pirâmides de Quéops, Quéfren e Miquerinos e a Esfinge" /><figcaption className="photo-credit">Esquema ilustrativo do planalto de Gizé, fora de escala.</figcaption></figure></div>
      <FactGrid facts={[{ title: 'Uma necrópole', text: 'Gizé faz parte de uma área muito maior de cemitérios e monumentos antigos.' }, { title: 'Templos', text: 'Karnak e Luxor foram ampliados por governantes de diferentes gerações.' }, { title: 'Núbia', text: 'Templos como Abu Simbel foram deslocados no século XX para protegê-los das águas do Lago Nasser.' }]} />
      <h2 id="tour">Faça um tour pelas imagens</h2><p className="body-copy">Acompanhe detalhes de uma cabeça real, de sinais talhados em pedra e de uma imagem de Osíris. Abra as fichas para ver contexto, datação e créditos do acervo.</p><p className="body-copy"><a className="cta" href="https://giza.fas.harvard.edu/giza3d/?itemID=bwZfJsv1_" target="_blank" rel="noreferrer">Abrir tour 3D da Pirâmide de Quéops · Harvard ↗</a></p><p className="photo-credit">O tour interativo foi desenvolvido pelo Giza Project, da Universidade Harvard, e requer internet.</p>
      <div className="object-gallery"><ObjectCard image="/assets/tutankhamun-head.jpg" alt="Cabeça esculpida de Tutancâmon" title="Cabeça de Tutancâmon" text="Peça do Novo Império." credit="Ficha do The Met" href="https://www.metmuseum.org/art/collection/search/544690" /><ObjectCard image="/assets/hieroglyphs.jpg" alt="Relevo com sinais hieroglíficos" title="Um relevo inacabado" text="As marcas permitem observar o trabalho do escultor." credit="Ficha do The Met" href="https://www.metmuseum.org/art/collection/search/562008" /><ObjectCard image="/assets/osiris.jpg" alt="Estatueta de Osíris" title="Osíris" text="Uma das divindades do panteão egípcio." credit="Ficha do The Met" href="https://www.metmuseum.org/art/collection/search/570658" /></div>
    </section><PageNext previous={{ text: 'Estação anterior: o Nilo', href: '/nilo.html' }} next={{ text: 'Próxima estação: escrita e crenças', href: '/escrita.html' }} /></div></section></main>;
}

export function WritingPage() {
  return <main id="conteudo"><PageHero page="writing" eyebrow="Sinais e histórias" title="Palavras gravadas em pedra">Escribas registravam nomes, oferendas e histórias com sistemas de escrita que mudaram ao longo do tempo.</PageHero><section className="page-content"><div className="wrap">
    <section aria-labelledby="sistemas-escrita"><div className="page-grid"><div><div className="section-kicker">Hieróglifos e outros sistemas</div><h2 id="sistemas-escrita">Uma escrita feita de sinais</h2><p className="body-copy">Os hieróglifos combinavam sinais que podiam representar sons, palavras ou ideias. Também existiram outras escritas egípcias, como a hierática e a demótica, usadas em contextos e períodos diferentes.</p><p className="body-copy">Os sinais podiam ser lidos em mais de uma direção. A orientação das figuras — por exemplo, para onde olham pessoas e animais — ajuda a indicar por onde começar.</p><h3 id="rosetta">A Pedra de Roseta</h3><p className="body-copy">A pedra traz um decreto de 196 a.C. registrado em hieróglifos, demótico e grego antigo. Como estudiosos conseguiam ler o grego, as versões ajudaram a decifrar os sinais egípcios. São três escritas que registram o texto em duas línguas.</p><div className="callout"><p><strong>Experimente:</strong> escolha um cartucho ou uma inscrição na imagem. Que detalhes se repetem? Que pistas ajudam a separar nomes e palavras?</p></div></div><figure><img src="/assets/hieroglyphs.jpg" alt="Detalhe de linhas de hieróglifos esculpidas em um bloco de pedra" loading="lazy" /><figcaption className="photo-credit">“Unfinished hieroglyphs”, bloco de relevo de Tebas. <a href="https://www.metmuseum.org/art/collection/search/562008" target="_blank" rel="noreferrer">The Met, objeto 20.3.160</a> · imagem CC0.</figcaption></figure></div></section>
    <section aria-labelledby="crencas"><div className="section-kicker">Deuses e outros mundos</div><h2 id="crencas">Deuses, rituais e vida após a morte</h2><p className="body-copy">Os egípcios cultuaram muitas divindades. Seus papéis e sua importância mudaram entre cidades e épocas; esta seleção é um guia rápido, não uma lista completa.</p><h3 className="subsection-title">Dez divindades para conhecer</h3><p className="body-copy deity-hint">Escolha uma divindade para abrir sua ficha. Use as setas para seguir conhecendo as outras.</p><DeityGallery />
      <h3 className="subsection-title afterlife-title">Uma jornada em três momentos</h3><div className="afterlife-steps">
        <article><span>01 · PREPARAR</span><h4>Cuidar do corpo</h4><p>Embalsamamento, caixão e objetos funerários ajudavam a preparar e proteger a pessoa. As práticas dependiam da época e dos recursos da família.</p></article>
        <article><span>02 · ACOMPANHAR</span><h4>Oferecer proteção</h4><p>Orações, amuletos, oferendas e rituais — como a Abertura da Boca — apoiavam a passagem e a continuidade da vida no além.</p></article>
        <article><span>03 · ATRAVESSAR</span><h4>Enfrentar o julgamento</h4><p>Em uma cena conhecida, Anúbis confere o coração diante da pena de Maat, Tot registra o resultado e Osíris preside o julgamento.</p></article>
      </div>
      <aside className="callout"><p><strong>Um detalhe:</strong> “Livro dos Mortos” é um nome moderno para coleções de fórmulas funerárias. Os textos variavam; não existia uma edição única usada por todos. As crenças também mudaram ao longo de milênios.</p></aside>
      <div className="page-grid deity-feature"><figure><img src="/assets/osiris.jpg" alt="Pequena estatueta de Osíris, de pé e usando a coroa Atef" loading="lazy" /><figcaption className="photo-credit">Estatueta de Osíris, período tardio ou ptolemaico. <a href="https://www.metmuseum.org/art/collection/search/570658" target="_blank" rel="noreferrer">The Met, objeto 04.2.579</a> · imagem CC0.</figcaption></figure><div><h3>Osíris e a renovação</h3><p className="body-copy">Osíris era associado à realeza, à vida após a morte e à regeneração. Sua imagem como figura mumificada expressava a esperança de continuidade além da morte.</p><p className="body-copy">Esta é uma estatueta de coleção, não uma ilustração moderna. Explore a ficha do museu para ver materiais e datação.</p></div></div>
    </section><PageNext previous={{ text: 'Estação anterior: monumentos', href: '/monumentos.html' }} next={{ text: 'Próxima estação: linha do tempo', href: '/linha-do-tempo.html' }} /></div></section></main>;
}

export function TimelinePage() {
  return <main id="conteudo"><PageHero page="timeline" eyebrow="Muitas épocas" title="Uma história maior que as pirâmides">As pirâmides são apenas um capítulo. A história do Egito atravessa milênios e segue no presente.</PageHero><section className="timeline" aria-labelledby="linha-periodos"><div className="wrap"><div className="section-kicker">Uma jornada em capítulos</div><h2 className="section-title" id="linha-periodos">Do reino antigo ao país contemporâneo</h2><p className="intro">Siga os capítulos em ordem ou escolha um período para explorar. As datas são aproximadas e podem variar entre fontes históricas.</p>
    <TimelineFilters /><div className="callout"><p>Uma linha do tempo resume uma história complexa. Ela não inclui todas as dinastias, comunidades, culturas e experiências que formaram o Egito.</p></div><PageNext previous={{ text: 'Estação anterior: escrita', href: '/escrita.html' }} next={{ text: 'Próxima estação: Egito hoje', href: '/egito-hoje.html' }} /></div></section></main>;
}

function TimelineFilters() {
  const [filter, setFilter] = useState('todos');
  const filters: Array<[string, string]> = [['todos', 'Jornada completa'], ['faraonico', 'Reinos faraônicos'], ['ptolomaico', 'Macedônio e ptolemaico'], ['romano', 'Roma e Bizâncio'], ['medieval', 'Período medieval'], ['moderno', 'Egito moderno']];
  const eras = timelineEras.map((era) => ({ ...era, events: era.events.filter((event) => filter === 'todos' || event.period === filter) })).filter((era) => era.events.length);
  const count = eras.reduce((total, era) => total + era.events.length, 0);
  return <><div className="filterbar" role="group" aria-label="Filtrar capítulos da linha do tempo">{filters.map(([value, label]) => <button type="button" className={filter === value ? 'active' : undefined} aria-pressed={filter === value} aria-controls="timeline-chapters" key={value} onClick={() => setFilter(value)}>{label}</button>)}</div><p className="timeline-count" id="timeline-count" aria-live="polite" aria-atomic="true">{count} {count === 1 ? 'marco histórico' : 'marcos históricos'}</p><div id="timeline-chapters">{eras.map((era) => <section className="timeline-era" data-era={era.id} aria-labelledby={era.headingId} key={era.id}><div className="era-heading"><span>{era.chapter}</span><h3 id={era.headingId}>{era.title}</h3><p>{era.description}</p></div><div className="timeline-list">{era.events.map((event) => <article className={`event${event.key ? ' is-key' : ''}`} data-period={event.period} key={event.title}><div className="dot" aria-hidden="true" /><div className="event-content"><time className="date">{event.date}</time><h4>{event.title}</h4><p>{event.description}</p><span className="period">{event.label}</span></div></article>)}</div></section>)}</div></>;
}

export function ModernPage() {
  return <main id="conteudo"><PageHero page="modern" eyebrow="Passado e presente" title="O Egito é mais do que seu passado antigo">Uma sociedade viva, com cidades, culturas e histórias que continuam mudando.</PageHero><section className="page-content"><div className="wrap">
    <section aria-labelledby="historia-moderna"><div className="section-kicker">História moderna</div><h2 id="historia-moderna">Da monarquia à república</h2><p className="body-copy">O Egito moderno passou por transformações políticas profundas. Em 1922, o Reino Unido declarou o reconhecimento da independência egípcia, mas manteve influência em questões importantes. Em 1952, uma revolução encerrou a monarquia; a república foi proclamada no ano seguinte.</p><p className="body-copy">O Canal de Suez, inaugurado no século XIX, liga o Mediterrâneo ao Mar Vermelho e é uma rota estratégica para a navegação. Depois de ficar fechado desde a guerra de 1967, reabriu ao tráfego internacional em 1975.</p><FactGrid facts={[{ title: 'Cairo', text: 'A capital e uma das grandes metrópoles do continente africano.' }, { title: 'Nilo', text: 'O rio continua central para a água, a agricultura e a vida no país.' }, { title: 'Patrimônio vivo', text: 'Monumentos antigos existem ao lado de bairros, mercados e cidades atuais.' }]} /></section>
    <section aria-labelledby="egito-vivo"><h2 id="egito-vivo">O antigo e o contemporâneo se encontram</h2><p className="body-copy">A população do Egito não vive em um cenário parado no tempo. Pessoas estudam, trabalham, criam arte, praticam religiões diversas e participam de uma sociedade moderna. Museus e sítios arqueológicos são parte de uma história ampla, que inclui também tradições árabes, islâmicas, coptas e muitas experiências regionais.</p><figure className="feature-photo"><img src="/assets/cairo-contemporary.jpg" alt="Ilustração contemporânea do Cairo junto ao Nilo, com edifícios, barcos e pontes" loading="lazy" /><figcaption className="photo-credit">Ilustração original feita para este site; não é fotografia de uma localização específica.</figcaption></figure><div className="callout"><p><strong>Uma pergunta para conversar:</strong> como podemos admirar monumentos antigos e, ao mesmo tempo, conhecer as pessoas e os desafios do Egito de hoje?</p></div></section>
    <PageNext previous={{ text: 'Estação anterior: linha do tempo', href: '/linha-do-tempo.html' }} next={{ text: 'Fazer o quiz do museu', href: '/index.html#quiz' }} />
  </div></section></main>;
}
